var searchData=
[
  ['addref_797',['AddRef',['../classspla_1_1RefCnt.html#a4baf8cce74f6ba7900e7d7fbe03876aa',1,'spla::RefCnt']]],
  ['algorithmmanager_798',['AlgorithmManager',['../classspla_1_1AlgorithmManager.html#a5200de80f5e2dd907c4f73f43d0a6398',1,'spla::AlgorithmManager']]],
  ['apply_799',['Apply',['../classspla_1_1detail_1_1ReduceOp.html#a03c096ae557b9bdf38e22bcf327ad2cb',1,'spla::detail::ReduceOp']]],
  ['applymask_800',['ApplyMask',['../group__Internal.html#ga00300e2b3dde5d373d7d9e1d307748c8',1,'spla::ApplyMask(const boost::compute::vector&lt; unsigned int &gt; &amp;mask, const boost::compute::vector&lt; unsigned int &gt; &amp;inputRows, const boost::compute::vector&lt; unsigned char &gt; &amp;inputVals, boost::compute::vector&lt; unsigned int &gt; &amp;outputRows, boost::compute::vector&lt; unsigned char &gt; &amp;outputVals, std::size_t byteSize, bool complement, boost::compute::command_queue &amp;queue)'],['../group__Internal.html#ga253e4c02d64c7faa8ccc9b7b957ade87',1,'spla::ApplyMask(const boost::compute::vector&lt; unsigned int &gt; &amp;maskRows, const boost::compute::vector&lt; unsigned int &gt; &amp;maskCols, const boost::compute::vector&lt; unsigned int &gt; &amp;inputRows, const boost::compute::vector&lt; unsigned int &gt; &amp;inputCols, const boost::compute::vector&lt; unsigned char &gt; &amp;inputVals, boost::compute::vector&lt; unsigned int &gt; &amp;outputRows, boost::compute::vector&lt; unsigned int &gt; &amp;outputCols, boost::compute::vector&lt; unsigned char &gt; &amp;outputVals, std::size_t byteSize, bool complement, boost::compute::command_queue &amp;queue)']]],
  ['as_801',['As',['../classspla_1_1RefPtr.html#a5d38314bb037fa4890e77b69dc110931',1,'spla::RefPtr']]],
  ['assign_802',['Assign',['../classspla_1_1detail_1_1binop_1_1Assign.html#a70bf0b2c9f590552dbf04ae5734e69cd',1,'spla::detail::binop::Assign']]]
];
