name: Self-Hosted

on:
  push:
    branches:
      - k.oreshin/test-branch
    paths:
      - '.github/**'
      - 'deps/**'
      - 'include/**'
      - 'src/**'
      - 'tests/**'
      - 'examples/**'
      - 'python/**'
      - '.gitignore'
      - '.gitmodules'
      - 'CMakeLists.txt'
  pull_request:
    branches: [ main ]

env:
  build-dir: "build"

jobs:
  test:
    name: Test GPU ${{ matrix.gpu }}
    runs-on: self-hosted

    steps:
      - name: Check for gpus
        run: |
          clinfo -l

      - name: Check for nvidia
        run: |
          nvidia-smi

      - name: Check for cuda
        run: |
          nvcc --version

  clean:
    name: Cleanup workspace
    needs: test
    if: always()
    runs-on: self-hosted

    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ${{ github.workspace }}/*
          rm -rf ${{ github.workspace }}/.*
