name: Run Tests

on:
  push:
    branches: [ master, koreshin/self-hosted-runner ]
  pull_request:
    branches: [ master ]

env:
  build_dir: "build"
  config: "Release"

jobs:
  build:
    name: Build library
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Configure CMake
        run: cmake . -G Ninja -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
        env:
          CC: gcc-13
          CXX: g++-13

      - name: Build library sources
        run: cmake --build ${{ env.build_dir }}

  test:
    name: Run tests
    needs: build
    runs-on: self-hosted
    timeout-minutes: 2

    steps:
      - name: Run tests
        run: |
        python3 ./run_tests.py --build-dir=${{ env.build_dir }} | tee >(grep -qE "FAILED|ERROR" && echo "HAS_ERRORS=true" >> $GITHUB_ENV)
        if [[ $HAS_ERRORS == "true" ]]; then
          exit 1
        fi
